#!/usr/bin/env bash

usage="$(basename $0) <docker_image> <container_name>"

fail()
{
  echo $1
  exit 1
}

set -e

# Verify early that we can run sudo.
sudo true
[ $? -eq 0 ] || fail "Running sudo failed."

[ -n "${HOME}" ] || fail "HOME is not set."
[ $# -eq 2 ] || fail "Not enough parameters: ${usage}"
docker_image=${1}; shift
container_name=${1}; shift

# Select a random free port.
free_port=`netstat -aln | awk '
  $6 == "LISTEN" {
    if ($4 ~ "[.:][0-9]+$") {
      split($4, a, /[:.]/);
      port = a[length(a)];
      p[port] = 1
    }
  }
  END {
    srand();
    start = int(3000 + rand()*10000);
    for (i = start; i < 65000 && p[i]; i++){};
    if (i == 65000) {exit 1};
    print i
  }
'`

sudo docker run \
  --name ${container_name} \
  --init \
  --cap-add=SYS_PTRACE \
  --network=host \
  -u $(whoami) \
  -d \
  -t \
  -v ${HOME}/.ssh:/home/$(whoami)/.ssh:Z \
  ${docker_image}

branch_name=${container_name}
sudo docker exec -u $(whoami) ${container_name} /home/$(whoami)/bin/start_ats_project ${branch_name}

echo
echo "Enter the container with:"
echo "sudo docker exec -it -u $(whoami) ${container_name} /bin/bash"
echo
echo "Enter the tmux session with:"
echo "tmux attach -t ${branch_name}"
