#!/usr/bin/env bash

fail()
{
  echo "Failed: $*"
  exit 1
}

[ $# -eq 1 ] || fail "Usage: $0 <new_repo_name>"
repo_name=$1
[ -d $repo_name ] && fail "Repo $repo_name already exists"

git clone git@github.com:bneradt/trafficserver.git ${repo_name}
cd ${repo_name}
git remote add upstream git@github.com:apache/trafficserver.git

git checkout master
git pull upstream master
git push origin master
