#!/usr/bin/env python3

import argparse
import json
import sys
from collections import OrderedDict


def parse_args():
    parser = argparse.ArgumentParser(description='Pretty print a json file.')
    parser.add_argument('jsonfile', type=argparse.FileType('r'), default=sys.stdin)
    return parser.parse_args()


def main():
    args = parse_args()
    content = json.load(args.jsonfile, object_pairs_hook=OrderedDict)
    print(json.dumps(content, sort_keys=False, indent=4))


if __name__ == '__main__':
    sys.exit(main())
