#!/usr/bin/env bash

usage="$(basename $0) <branch_name>"

fail()
{
  echo $1
  exit 1
}

[ -n "${HOME}" ] || fail "HOME is not set."
[ $# -eq 1 ] || fail "Not enough parameters: ${usage}"
branch_name=${1}; shift

srcdir=${HOME}/src
repo_name=ts_asf_master_${branch_name}
ts_src=${srcdir}/${repo_name}

set -e
set -x

mkdir -p ${srcdir}
cd ${srcdir}
[ -d "${repo_name}" ] && fail "${srcdir}/${repo_name} already exists"

# Assume the user has a fork using their username.
git clone git@github.com:$(whoami)/trafficserver.git $repo_name
cd $repo_name
git remote add upstream git@github.com:apache/trafficserver.git
git remote update
git checkout master
git pull upstream master
git push origin master
git checkout -b ${branch_name}

tmux new-session -s ${branch_name}   -n "src" -d "cd ${ts_src}; bash -i"
tmux new-window  -t ${branch_name}:1 -n "build"  "cd ${ts_src}; bash -i"
tmux new-window  -t ${branch_name}:2 -n "test"   "cd ${ts_src}/tests; bash -i"

tmux select-window -t ${branch_name}:0
