#!/usr/bin/env bash

script_name=$(basename $0)
usage="${script_name} \<docker_image_name\>"

fail()
{
  echo $1
  exit 1
}

[ $# -eq 1 ] || fail "${usage}"
tag_name=$1

parent_dir=$(dirname $0)
ats_dockerfile_dir=${parent_dir}/../ats
[ -d "${ats_dockerfile_dir}" ] || fail "Could not find ATS Dockerfile: ${ats_dockerfile_dir}"
cd $ats_dockerfile_dir
sudo docker build \
  -t ${tag_name} \
  --build-arg "username=${USER}" \
  --build-arg "userid=$(id -u)" \
  .
