#!/usr/bin/env bash

# Build ATS using the /opt/openssl-quic version of OpenSSL.

set -e
set -x
expected_dirname="${HOME}/src"
fail()
{
  echo $1
  exit 1
}

openssl="/opt/openssl-quic"

repo_name=`basename $(pwd)`
build_dir="${HOME}/build/${repo_name}"
command="autoreconf -fi && ./configure --prefix ${build_dir} --with-openssl=${openssl}--enable-werror --enable-debug --enable-wccp"
dirname=$(dirname $(pwd))
[ "${dirname}" = "${expected_dirname}" ] || fail "Expected to be in: ${expected_dirname}. Not running: ${command}"

source /opt/rh/gcc-toolset-9/enable
# Make sure we get the quic-version of curl.
export PATH=/opt/bin:${PATH}
if [ -d "${build_dir}" ]
then
  while true; do
    read -p "${build_dir} already exists. Clean it? (y/n) " yn
    case $yn in
        [Yy]* ) break;;
        [Nn]* ) exit 0;;
        * ) echo "Please answer y or n.";;
    esac
  done

  git clean -d -x -f -q
  rm -rf ${build_dir}
fi
autoreconf -fi
./configure --prefix ${build_dir} --with-openssl=${openssl} --enable-werror --enable-debug --enable-wccp
bear -- make -j $(nproc)
make install
