#!/usr/bin/env bash

tmpdir=/tmp/build_static.$$
buildout=${tmpdir}/build_output.txt
static_command=${tmpdir}/static_command.sh

fail()
{
  echo $1
  exit 1
}

set -x
set -e

uname -a | grep Linux || fail "Currently this only works on Linux."
[ -f Sconstruct ] || fail "Not in the root directory of proxy-verifier."

if ! pipenv --venv > /dev/null 2>&1
then
  pipenv install
fi

for i in `find . -name verifier-client -type f`; do rm $i; done
for i in `find . -name verifier-server -type f`; do rm $i; done

mkdir -p ${tmpdir}
pipenv run scons -j$(nproc) --with-libs=/opt | tee ${buildout}

grep -E 'verifier-(client|server) ' ${buildout} | \
  sed 's/-o /-static -o /g' | \
  sed 's/-Wl,-rpath[^ ]\+//g' | \
  sed 's/-lpthread //g' | \
  sed 's/$/ -Wl,--whole-archive -lpthread -Wl,--no-whole-archive -ldl/g' > \
  ${static_command}

for i in `find . -name verifier-client -type f`; do rm $i; done
for i in `find . -name verifier-server -type f`; do rm $i; done

bash ${static_command}

for f in $(grep -E -o '\S*/verifier-(client|server) ' ${buildout})
do
  cp $f bin/
done

strip bin/verifier-*

rm -rf ${tmpdir}
