#!/usr/bin/env bash

script_name=$(basename $0)
usage="${script_name} \<docker_image_name\>"

tmpdir=/tmp/docker_image_create_$$

fail()
{
  echo $1
  exit 1
}

[ $# -eq 1 ] || fail "${usage}"
tag_name=$1

parent_dir=$(dirname $0)
ats_dockerfile_dir=${parent_dir}/../Dockerfiles/ats
[ -d "${ats_dockerfile_dir}" ] || fail "Could not find ATS Dockerfile: ${ats_dockerfile_dir}"

context_dir=${parent_dir}/../docker_context
[ -d "${context_dir}" ] || fail "Could not find ATS context directory: ${context_dir}"
if [ "${USER}" != "bneradt" ]
then
  gitconfig=${context_dir}/.gitconfig
  if grep -q "eradt" "${gitconfig}"
  then
    fail "Modify ${gitconfig} to have your name and username."
  fi
fi

mkdir -p ${tmpdir}
cp -rf ${ats_dockerfile_dir}/* ${tmpdir}
cp ${context_dir}/.* ${tmpdir}

cd $tmpdir
sudo docker build \
  -t ${tag_name} \
  --build-arg "username=${USER}" \
  --build-arg "userid=$(id -u)" \
  .

rm -rf $tmpdir
