#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags"' EXIT
git ls-files `dirname ${dir}` | \
  ctags --tag-relative -L - -f"$dir/$$.tags" --c++-kinds=+p --fields=+iaS --extra=+q+f
mv "$dir/$$.tags" "$dir/tags"
