#!/usr/bin/env bash

usage="$(basename $0) <branch_name>"

fail()
{
  echo $1
  exit 1
}

[ -n "${HOME}" ] || fail "HOME is not set."
[ $# -eq 1 ] || fail "Not enough parameters: ${usage}"
branch_name=${1}; shift

srcdir=${HOME}/src
repo_clone_name=toy-${branch_name}
ts_src=${srcdir}/${repo_clone_name}

set -e
set -x

mkdir -p ${srcdir}
cd ${srcdir}
[ -d "${repo_clone_name}" ] && fail "${srcdir}/${repo_clone_name} already exists"

# Assume the user has a fork using their username.
my_repo_fork=git@github.com:bneradt/toy.git
git clone $my_repo_fork $repo_clone_name
cd $repo_clone_name
if git ls-remote --exit-code --heads ${my_repo_fork} ${branch_name} > /dev/null
then
  # The branch exists. Check it out.
  git checkout ${branch_name}
else
  # The branch does not exist yet. Create it.
  git checkout -b ${branch_name}
fi

tmux new-session -s ${branch_name}   -n "src" -d "cd ${ts_src}; bash -i"
tmux new-window  -t ${branch_name}:1 -n "test"   "cd ${ts_src}/tests; bash -i"

tmux select-window -t ${branch_name}:0
